# Generated by Django 3.1.7 on 2021-03-03 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='now_weight',
        ),
        migrations.AddField(
            model_name='cook',
            name='now_weight',
            field=models.PositiveSmallIntegerField(blank=True, default=0, verbose_name='Сколько осталось блюда'),
        ),
    ]
