# Generated by Django 3.1.7 on 2021-02-26 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cook',
            old_name='cook_ingredient',
            new_name='cook_ingredients',
        ),
    ]
