# Generated by Django 3.1.7 on 2021-03-01 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0002_auto_20210301_0101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cookingredient',
            name='count_use',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Сколько используется в блюде'),
        ),
    ]
