# Generated by Django 3.1.7 on 2021-03-03 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0004_auto_20210303_2025'),
    ]

    operations = [
        migrations.AddField(
            model_name='cook',
            name='is_overdue',
            field=models.BooleanField(default=False, verbose_name='Просрочилось?'),
        ),
    ]
