# Generated by Django 3.1.7 on 2021-03-03 20:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0005_cook_is_overdue'),
    ]

    operations = [
        migrations.AddField(
            model_name='cook',
            name='date',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='Когда приготовлено?'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='days_to_overdue',
            field=models.PositiveSmallIntegerField(default=3, verbose_name='Сколько дней до просрочки'),
        ),
    ]
