# Generated by Django 3.1.7 on 2021-03-03 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0006_auto_20210303_2319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='days_to_overdue',
            field=models.PositiveSmallIntegerField(verbose_name='Сколько дней до просрочки'),
        ),
    ]
