# Generated by Django 3.1.7 on 2021-03-02 20:44

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import main.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('food', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(blank=True, upload_to=main.models.get_path_for_avatar, verbose_name='Аватарка')),
                ('calories_limit', models.PositiveSmallIntegerField(verbose_name='Лимит калорий в день')),
                ('calories_now', models.PositiveSmallIntegerField(blank=True, default=0, verbose_name='Сколько употреблено на сегодня')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Объект пользователя')),
            ],
            options={
                'verbose_name': 'Профиль',
                'verbose_name_plural': 'Профили',
            },
        ),
        migrations.CreateModel(
            name='EatCook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count_eat', models.PositiveSmallIntegerField(verbose_name='Сколько грамм употреблено')),
                ('calories_eat', models.PositiveSmallIntegerField(default=0, verbose_name='Сколько калорий употреблено')),
                ('date', models.DateTimeField(default=datetime.datetime.now, verbose_name='Когда употреблено')),
                ('cook', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='food.cook', verbose_name='Блюдо')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_eat_cook', to='main.profile', verbose_name='Профиль')),
            ],
            options={
                'verbose_name': 'Употребленное блюдо',
                'verbose_name_plural': 'Употребленное блюда',
            },
        ),
    ]
