# Generated by Django 3.1.7 on 2021-03-03 19:50

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0005_cook_is_overdue'),
        ('main', '0003_auto_20210303_1634'),
    ]

    operations = [
        migrations.CreateModel(
            name='EatIngredient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=datetime.datetime.now, verbose_name='Когда употреблено')),
                ('count_eat', models.PositiveSmallIntegerField(verbose_name='Сколько грамм употреблено')),
                ('calories_eat', models.PositiveSmallIntegerField(blank=True, default=0, verbose_name='Сколько калорий употреблено')),
                ('ingredient_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='food.ingredientitem', verbose_name='Продукт')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_eat_ingredient', to='main.profile', verbose_name='Профиль')),
            ],
            options={
                'verbose_name': 'Употребленный продукт',
                'verbose_name_plural': 'Употребленные продукты',
            },
        ),
    ]
